apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pg-broker-cluster-role
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - list
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - update
  - delete
  - list
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - update
  - delete
  - list
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - update
  - list
  - delete
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - delete
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - update
  - list
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - update
  - list
---
# Bind to the default service account
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pg-broker-cluster-rolebinding
roleRef:
  kind: ClusterRole
  name: pg-broker-cluster-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}