apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-config-{{ .Instance_id}}
data:
  init.sh: | 
    #!/bin/bash
    echo "shared_preload_libraries = 'pg_stat_statements'" >> $PGDATA/postgresql.conf
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    create extension pg_stat_statements;
    EOSQL
    