apiVersion: v1
data:
  pg_password: "{{ .Pg_password}}"
kind: Secret
metadata:
  labels:
    app: postgres-{{ .Instance_id}}
    release: postgres-{{ .Instance_id}}
  name: postgres-{{ .Instance_id}}
type: Opaque
